AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

#Enable these when we want to start heavy refactoring
Layout/LineLength:
  Enabled: false
  Max: 100
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength: 
  Max: 250
# Rails/HasAndBelongsToMany:
  # Enabled: false

#Enable these once java is gone
Naming/VariableName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
  Max: 10

#until we are on rspec3
Lint/Void:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false